### PR TITLE
Update azure-deploy.json

### PR DESCRIPTION
**Pull request by Envera**
Both Fuction apps were using the same fileshare container for contain fuctions which was conflict.

we changed the fileshare name for funcionapp 
"TollBoothFunctions" for     "value": "[concat(variables('dataLakeAccountName'), 'functions']" 
"TollBoothEvents" for     "value": "[concat(variables('dataLakeAccountName'), 'Events']"

### CODE REVIEW

**Comment by daronyondem** [comment]
Interesting. We might even want to [remove that](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_contentshare). What did you experience that surfaced the conflict in your case?

**Comment by willlimtc** [comment]
I am experiencing the similar issue. Once I have published to the ToollBothFunctions app from visual studio. The TollBoothEvents function rendered the runtime error Microsoft.Azure.WebJobs.Script: Did not find functions with language [node]. I suspect that the error comes from the fact that TollBoothFucnction and TollBoothEvent share the same storage account and/or app service plan that conflict with each other.

**Comment by Envera** [comment]
> Interesting. We might even want to [remove that](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_contentshare). What did you experience that surfaced the conflict in your case?

it causes functions like copied on the both of the FunctionApp Services. and they are not answering to eventgrid subscriptions triggers correctly thats because. and once you go in to "TollBoothEvents" it gives you an error "Microsoft.Azure.WebJobs.Script: Did not find functions with language [node]"

**Comment by Envera** [comment]
> > Interesting. We might even want to [remove that](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_contentshare). What did you experience that surfaced the conflict in your case?
> 
> it causes functions like copied on the both of the FunctionApp Services. and they are not answering to eventgrid subscriptions triggers correctly thats because. and once you go in to "TollBoothEvents" it gives you an error "Microsoft.Azure.WebJobs.Script: Did not find functions with language [node]"

You can Merge this code. currently I am doing the lab with a customer and it is working now.

**Pull request merged**
